import os

RAW_DB_URL = os.getenv("DATABASE_URL")

if RAW_DB_URL:
    if RAW_DB_URL.startswith("postgresql://"):
        SQLALCHEMY_DATABASE_URL = RAW_DB_URL.replace("postgresql://", "postgresql+asyncpg://", 1)
    else:
        SQLALCHEMY_DATABASE_URL = RAW_DB_URL
else:
    SQLALCHEMY_DATABASE_URL = "postgresql+asyncpg://postgres:IkdpEkjqksEZwovonLhKAEsylUJuXRME@postgres.railway.internal:5432/railway"

REDIS_URL = os.getenv("REDIS_URL", "redis://default:PrJNOtfmrVvedEbswYzILOvLggyGKdPk@redis.railway.internal:6379")

FRONTEND_URL = os.getenv("FRONTEND_URL", "http://localhost:3000")
SECRET_KEY = os.getenv("SECRET_KEY", "BuA2vBYUhflSbcaeaFZots2r89ez_W5WMV7nk28YgeY")

ADMIN_EMAILS = [
    "moddedgames200@gmail.com",
    "Abeeharaza22@gmail.com"
]

RESEND_API_KEY = os.getenv("RESEND_API_KEY", "re_XRhZRUM2_646GuJqERePVTmV2GeaJLLBM")
EMAIL_FROM = os.getenv("EMAIL_FROM", "noreply@aeroml.com")

LEMON_SQUEEZY_API_KEY = os.getenv("LEMON_SQUEEZY_API_KEY", "eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiI5NGQ1OWNlZi1kYmI4LTRlYTUtYjE3OC1kMjU0MGZjZDY5MTkiLCJqdGkiOiI5MTdmN2FlMDM5ZmFlMjE2ZTMyYjVjNmQ0ZDFlYTMzMWRmMmY4M2RkY2E2NmE3ZjIzMzkzZGUzNmMwM2U2YTNmYWJlNjg5MTczNTIxOWJhZiIsImlhdCI6MTc4MzI3NDUzMS40ODQ2NzMsIm5iZiI6MTc4MzI3NDUzMS4")
LEMON_SQUEEZY_STORE_ID = os.getenv("LEMON_SQUEEZY_STORE_ID", "your_store_id_here")
LEMON_SQUEEZY_WEBHOOK_SECRET = os.getenv("LEMON_SQUEEZY_WEBHOOK_SECRET", "abc123xyz789securewebhook")
LEMON_SQUEEZY_VARIANT_ID = os.getenv("LEMON_SQUEEZY_VARIANT_ID", "1873242")
LEMON_SQUEEZY_PRODUCT_ID = os.getenv("LEMON_SQUEEZY_PRODUCT_ID", "1198213")

TRIAL_DURATION_HOURS = 24
PREMIUM_DURATION_DAYS = 30
PREMIUM_PRICE_MONTHLY = 19.00

RATE_LIMIT_PER_MINUTE = 100
RATE_LIMIT_SIGNUP_PER_HOUR = 5

CELERY_BROKER_URL = os.getenv("CELERY_BROKER_URL", REDIS_URL)
CELERY_RESULT_BACKEND = os.getenv("CELERY_RESULT_BACKEND", REDIS_URL)

class Settings:
    def __init__(self):
        self.SQLALCHEMY_DATABASE_URL = SQLALCHEMY_DATABASE_URL
        self.REDIS_URL = REDIS_URL
        self.FRONTEND_URL = FRONTEND_URL
        self.SECRET_KEY = SECRET_KEY
        self.ADMIN_EMAILS = ADMIN_EMAILS
        self.RESEND_API_KEY = RESEND_API_KEY
        self.EMAIL_FROM = EMAIL_FROM
        self.LEMON_SQUEEZY_API_KEY = LEMON_SQUEEZY_API_KEY
        self.LEMON_SQUEEZY_STORE_ID = LEMON_SQUEEZY_STORE_ID
        self.LEMON_SQUEEZY_WEBHOOK_SECRET = LEMON_SQUEEZY_WEBHOOK_SECRET
        self.LEMON_SQUEEZY_VARIANT_ID = LEMON_SQUEEZY_VARIANT_ID
        self.LEMON_SQUEEZY_PRODUCT_ID = LEMON_SQUEEZY_PRODUCT_ID
        self.TRIAL_DURATION_HOURS = TRIAL_DURATION_HOURS
        self.PREMIUM_DURATION_DAYS = PREMIUM_DURATION_DAYS
        self.PREMIUM_PRICE_MONTHLY = PREMIUM_PRICE_MONTHLY
        self.RATE_LIMIT_PER_MINUTE = RATE_LIMIT_PER_MINUTE
        self.RATE_LIMIT_SIGNUP_PER_HOUR = RATE_LIMIT_SIGNUP_PER_HOUR
        self.CELERY_BROKER_URL = CELERY_BROKER_URL
        self.CELERY_RESULT_BACKEND = CELERY_RESULT_BACKEND

settings = Settings()
